services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spark-net
      
  producer:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: producer
    depends_on:
      - kafka
    command: >
      bash -c "until (echo > /dev/tcp/kafka/9092) >/dev/null 2>&1; do echo 'Waiting for kafka:9092...'; sleep 1; done; sleep 3; python3 /app/kafka/topics.py && python3 /app/kafka/producer.py"
    volumes:
      - ./kafka:/app/kafka
      - ./data/blacklist.txt:/app/data/blacklist.txt
      - ./utils:/app/utils
    networks:
      - spark-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - spark-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - spark-net

  volume-init:
    image: busybox:1.36
    container_name: volume-init
    command: >
      sh -c "mkdir -p /app/data/raw /app/data/transformed && chmod -R 777 /app/data/raw /app/data/transformed"
    volumes:
      - raw_data:/app/data/raw
      - transformed_data:/app/data/transformed
    networks:
      - spark-net

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark.cluster
    image: packet-analyzer-spark-cluster:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    depends_on:
      volume-init:
        condition: service_completed_successfully
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - spark-net
    volumes:
      - ./spark:/app/spark
      - raw_data:/app/data/raw
      - transformed_data:/app/data/transformed
      - ./data/blacklist.txt:/app/data/blacklist.txt
      - ./utils:/app/utils
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master"

  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile.spark.cluster
    image: packet-analyzer-spark-cluster:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_DIR=/tmp/spark/work
      - SPARK_LOCAL_DIRS=/tmp/spark/local
    depends_on:
      spark-master:
        condition: service_started
      volume-init:
        condition: service_completed_successfully
    ports:
      - "8081:8081"
    networks:
      - spark-net
    volumes:
      - ./spark:/app/spark
      - raw_data:/app/data/raw
      - transformed_data:/app/data/transformed
      - ./data/blacklist.txt:/app/data/blacklist.txt
      - ./utils:/app/utils
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"

  airflow:
    user: "50000:0"
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow
    depends_on:
      kafka:
        condition: service_started
      spark-master:
        condition: service_started
      postgres:
        condition: service_started
      volume-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW_HOME=/app/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.www.security.DefaultAuthBackend
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/tmp/airflow_logs
      - AIRFLOW__CORE__XCOM_BACKEND=airflow.models.xcom.BaseXCom
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./airflow:/app/airflow
      - ./spark:/app/spark
      - raw_data:/app/data/raw
      - transformed_data:/app/data/transformed
      - ./data/blacklist.txt:/app/data/blacklist.txt
      - ./data/transformed:/app/export/transformed
      - ./utils:/app/utils
    ports:
      - "8088:8080"
    command: >
      bash -c "until (echo > /dev/tcp/postgres/5432) >/dev/null 2>&1; do echo 'Waiting for postgres:5432...'; sleep 1; done; mkdir -p /tmp/airflow_logs && airflow db migrate && airflow connections create-default-connections && { airflow scheduler & exec airflow webserver; }"
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
volumes:
  postgres_data:
  raw_data:
  transformed_data: